title: "AU98 Tech Guides"
description: "Guides for setting up and getting the best configuration for various software"
markdown: GFM
show_downloads: false
repository: AnonymousUser98/guides
theme: minima

minima:
  social_links:
    - title: AnonymousUser98's GitHub Profile
      icon: github
      url: "https://github.com/AnonymousUser98"
    - title: GitHub Pages Website
      icon: globe
      url: "https://anonymoususer98.github.io"
  hide_site_feed_link: true

  date_format: "%B %e, %Y"

  nav_pages:
    - windows.md
    - android.md

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/

